/* ============================================================
   Interview questions library — 30 top questions per category,
   each with a concise, correct answer. Rendered by interview.js.
   Each item: { cat, q, a }
   ============================================================ */
window.INTERVIEW = [

  /* ===== JavaScript (30) ===== */
  { cat:"JavaScript", q:"What is the difference between var, let and const?", a:"var is function-scoped and hoisted as undefined. let and const are block-scoped and sit in a temporal dead zone until declared. const can't be reassigned, though objects it holds stay mutable." },
  { cat:"JavaScript", q:"What is the difference between == and ===?", a:"== compares after type coercion ('5' == 5 is true). === compares value and type with no coercion ('5' === 5 is false). Prefer ===." },
  { cat:"JavaScript", q:"What is a closure?", a:"A function that remembers variables from the scope where it was created, even after that scope has returned. It enables data privacy and factory functions." },
  { cat:"JavaScript", q:"Explain hoisting.", a:"Declarations are moved to the top of their scope before execution. var initialises as undefined, function declarations are fully hoisted, and let/const are hoisted but uninitialised (temporal dead zone)." },
  { cat:"JavaScript", q:"What is the event loop?", a:"It lets single-threaded JS handle async work: it runs the call stack, drains the microtask queue (promises), then takes one macrotask (timers/I/O), and repeats." },
  { cat:"JavaScript", q:"Promises vs async/await?", a:"Both handle async code. async/await is sugar over promises that reads top-to-bottom and uses try/catch for errors instead of .then().catch() chains." },
  { cat:"JavaScript", q:"null vs undefined?", a:"undefined means declared but not assigned; null is an intentional empty value. typeof undefined is 'undefined'; typeof null is 'object' (a historic quirk)." },
  { cat:"JavaScript", q:"How does 'this' work?", a:"'this' is the object that called the function, decided at call time. In a method it's the object; standalone it's undefined/global; arrow functions inherit it from the enclosing scope." },
  { cat:"JavaScript", q:"map() vs forEach()?", a:"map() returns a new transformed array and is chainable. forEach() just iterates and returns undefined. Use map for results, forEach for side effects." },
  { cat:"JavaScript", q:"What is event bubbling and delegation?", a:"Bubbling propagates an event from the target up through its ancestors. Delegation attaches one listener on a parent to handle many children efficiently." },
  { cat:"JavaScript", q:"Debounce vs throttle?", a:"Debounce waits until activity stops before running (search-as-you-type). Throttle runs at most once per interval (scroll handlers)." },
  { cat:"JavaScript", q:"Shallow vs deep copy?", a:"A shallow copy (spread, Object.assign) duplicates only the top level; nested objects are shared. A deep copy (structuredClone) duplicates every level." },
  { cat:"JavaScript", q:"localStorage vs sessionStorage vs cookies?", a:"localStorage persists until cleared; sessionStorage lasts for the tab; cookies are small and sent with each request. Use storage for client data, cookies for server-read auth." },
  { cat:"JavaScript", q:"What are arrow functions and how do they differ?", a:"Concise function syntax that has no own 'this', 'arguments', or prototype. They inherit 'this' lexically, so they're great for callbacks but unsuitable as methods or constructors." },
  { cat:"JavaScript", q:"call, apply and bind?", a:"All set 'this'. call invokes with comma-separated args, apply invokes with an args array, and bind returns a new function with 'this' permanently bound." },
  { cat:"JavaScript", q:"What is the spread and rest operator?", a:"Both use '...'. Spread expands an iterable into elements (copy/merge arrays or objects). Rest collects remaining arguments or values into an array." },
  { cat:"JavaScript", q:"What is destructuring?", a:"A syntax to unpack values from arrays or properties from objects into variables, e.g. const { name } = user or const [a, b] = arr." },
  { cat:"JavaScript", q:"What is a higher-order function?", a:"A function that takes a function as an argument or returns a function. map, filter, reduce and event handlers are common examples." },
  { cat:"JavaScript", q:"Synchronous vs asynchronous code?", a:"Synchronous code runs line by line, blocking until each finishes. Asynchronous code (callbacks, promises, async/await) lets long operations run without blocking the main thread." },
  { cat:"JavaScript", q:"What are template literals?", a:"Backtick strings that support multi-line text and interpolation with ${expression}, replacing clunky string concatenation." },
  { cat:"JavaScript", q:"slice() vs splice()?", a:"slice returns a shallow copy of a portion without changing the original. splice changes the original array by removing/inserting elements and returns the removed ones." },
  { cat:"JavaScript", q:"find() vs filter()?", a:"find returns the first element matching a condition (or undefined). filter returns a new array of all matching elements." },
  { cat:"JavaScript", q:"What is NaN and how do you check for it?", a:"NaN means 'Not a Number', the result of invalid math. Use Number.isNaN() to test it, since NaN is the only value not equal to itself." },
  { cat:"JavaScript", q:"What is type coercion?", a:"JavaScript automatically converting one type to another in operations, e.g. '5' + 1 becomes '51' (string) while '5' - 1 becomes 4 (number)." },
  { cat:"JavaScript", q:"Function declaration vs expression?", a:"A declaration (function foo(){}) is fully hoisted and callable before its line. An expression (const foo = function(){}) is only available after assignment." },
  { cat:"JavaScript", q:"What are the JavaScript data types?", a:"Seven primitives: string, number, bigint, boolean, undefined, null, symbol; plus the object type (arrays, functions, objects)." },
  { cat:"JavaScript", q:"What is the DOM?", a:"The Document Object Model — a tree representation of the HTML page that JavaScript can read and manipulate to change content, structure and styles." },
  { cat:"JavaScript", q:"Promise.all vs Promise.race?", a:"Promise.all waits for all promises and fails if any reject. Promise.race settles as soon as the first promise settles (resolve or reject)." },
  { cat:"JavaScript", q:"Optional chaining and nullish coalescing?", a:"?. safely reads nested properties, returning undefined instead of throwing. ?? provides a fallback only when the value is null or undefined (not for 0 or '')." },
  { cat:"JavaScript", q:"What does 'use strict' do?", a:"Enables strict mode, which catches silent errors (like undeclared variables), disables confusing features, and makes code safer and easier to optimise." },

  /* ===== React (30) ===== */
  { cat:"React", q:"What is the Virtual DOM?", a:"An in-memory copy of the real DOM. React diffs a new virtual tree against the old one (reconciliation) and updates only the real nodes that changed." },
  { cat:"React", q:"Props vs state?", a:"Props are read-only inputs from a parent. State is private, mutable data owned by a component. Changing either re-renders the component." },
  { cat:"React", q:"What does useEffect do?", a:"Runs side effects after render. The dependency array controls when it re-runs, and a returned function provides cleanup before the next run or on unmount." },
  { cat:"React", q:"Why are keys important in lists?", a:"Keys give items a stable identity so React can track adds, removes and reorders efficiently. Avoid array index as a key when the list can change order." },
  { cat:"React", q:"Controlled vs uncontrolled components?", a:"A controlled input's value comes from state (value + onChange). An uncontrolled input keeps its value in the DOM, read via a ref. Controlled is preferred." },
  { cat:"React", q:"useMemo vs useCallback?", a:"useMemo memoises a computed value; useCallback memoises a function reference. Both prevent unnecessary recalculation or re-renders." },
  { cat:"React", q:"What is the Context API?", a:"A built-in way to share data (theme, auth) across the tree without prop drilling, via a provider and useContext." },
  { cat:"React", q:"What is JSX?", a:"A syntax extension that lets you write HTML-like markup in JavaScript, compiled to React.createElement() calls." },
  { cat:"React", q:"Class vs functional components?", a:"Functional components with hooks are the modern standard — less boilerplate, easier logic reuse. Class components use lifecycle methods and are largely legacy." },
  { cat:"React", q:"What triggers a re-render?", a:"A state change, a prop change, a parent re-render, or a consumed context value changing. Optimise with memo, useMemo and useCallback when needed." },
  { cat:"React", q:"What is a custom hook?", a:"A reusable function starting with 'use' that encapsulates stateful logic (useFetch, useToggle), shared between components without changing hierarchy." },
  { cat:"React", q:"How do you optimise React performance?", a:"Memoise with React.memo/useMemo/useCallback, use stable keys, lazy-load with React.lazy/Suspense, virtualise long lists, and avoid inline objects that cause re-renders." },
  { cat:"React", q:"What are the rules of hooks?", a:"Only call hooks at the top level (not in loops, conditions or nested functions) and only from React functions. This keeps hook order consistent across renders." },
  { cat:"React", q:"What does useState do?", a:"It adds local state to a function component, returning the current value and a setter. Calling the setter schedules a re-render with the new value." },
  { cat:"React", q:"What is useRef used for?", a:"It holds a mutable value that persists across renders without causing re-renders — used to reference DOM nodes or store values like timers." },
  { cat:"React", q:"What is useReducer?", a:"A hook for complex state logic. You dispatch actions to a reducer function that returns the next state — like a local Redux pattern." },
  { cat:"React", q:"What is prop drilling and how do you avoid it?", a:"Passing props through many intermediate components that don't use them. Avoid it with the Context API or a state manager." },
  { cat:"React", q:"What is React Router?", a:"A library for client-side routing — it maps URLs to components so a single-page app can have multiple navigable views without full reloads." },
  { cat:"React", q:"What is reconciliation?", a:"React's diffing process that compares the new virtual DOM with the previous one and applies the minimal set of real DOM updates." },
  { cat:"React", q:"State vs ref — when to use each?", a:"Use state for values that should re-render the UI when they change. Use a ref for values you want to persist without triggering a render (DOM nodes, timers)." },
  { cat:"React", q:"What is lifting state up?", a:"Moving shared state to the closest common parent so sibling components can read and update it via props/callbacks." },
  { cat:"React", q:"What is a React Fragment?", a:"A wrapper (<></> or React.Fragment) that groups children without adding an extra DOM node." },
  { cat:"React", q:"What is lazy loading and Suspense?", a:"React.lazy splits a component into a separate bundle loaded on demand; Suspense shows a fallback (spinner) while it loads, improving initial load time." },
  { cat:"React", q:"What is the children prop?", a:"A special prop containing whatever you nest inside a component's tags, letting you build flexible, composable wrapper components." },
  { cat:"React", q:"How do you do conditional rendering?", a:"Use ternaries, logical && , or early returns in JSX to render different UI based on state or props." },
  { cat:"React", q:"What are synthetic events?", a:"React's cross-browser wrapper around native DOM events, giving a consistent API regardless of the browser." },
  { cat:"React", q:"What is React StrictMode?", a:"A development-only wrapper that highlights potential problems (deprecated APIs, side effects) by intentionally double-invoking certain functions." },
  { cat:"React", q:"How does useEffect cleanup work?", a:"Return a function from useEffect; React runs it before the effect re-runs and on unmount — used to clear timers, subscriptions and listeners." },
  { cat:"React", q:"What is React.memo?", a:"A higher-order component that memoises a component, skipping re-render when its props are unchanged (shallow comparison)." },
  { cat:"React", q:"How do you fetch data in React?", a:"Call fetch/axios inside a useEffect with an empty dependency array (or a data-fetching library like React Query), storing the result in state." },

  /* ===== React Native (30) ===== */
  { cat:"React Native", q:"How does React Native differ from React?", a:"React renders to the browser DOM; React Native renders to real native components (View, Text) on iOS/Android, producing true native apps from one JS codebase." },
  { cat:"React Native", q:"What is the bridge / new architecture?", a:"The bridge passes serialised async messages between JS and native code. The new architecture (JSI, Fabric, TurboModules) allows synchronous calls for better performance." },
  { cat:"React Native", q:"FlatList vs ScrollView?", a:"ScrollView renders all children at once (small content). FlatList lazily renders and recycles only visible items, essential for long lists." },
  { cat:"React Native", q:"How do you persist data locally?", a:"AsyncStorage for key-value data; SQLite, Realm, WatermelonDB or MMKV for structured or high-performance storage." },
  { cat:"React Native", q:"How do you handle platform differences?", a:"Use Platform.OS, Platform.select(), or platform-specific files (Button.ios.js / Button.android.js) that the bundler picks automatically." },
  { cat:"React Native", q:"What is Fast Refresh?", a:"A dev feature that instantly reflects code edits while preserving component state, speeding up the development loop." },
  { cat:"React Native", q:"How do you debug a React Native app?", a:"Use Flipper, React DevTools, the in-app dev menu, console logs and network inspectors; profile renders for performance." },
  { cat:"React Native", q:"How do you optimise RN performance?", a:"Use FlatList, memoise components, avoid inline functions/objects in render, size images correctly, enable Hermes, and minimise bridge traffic." },
  { cat:"React Native", q:"Expo vs React Native CLI?", a:"Expo is a managed workflow with prebuilt tooling and easy builds, great for speed. The CLI (bare) gives full native control and custom native modules." },
  { cat:"React Native", q:"What are the core components?", a:"Building blocks like View (container), Text, Image, TextInput, ScrollView and FlatList, which map to native UI elements." },
  { cat:"React Native", q:"What is StyleSheet?", a:"StyleSheet.create defines styles as JS objects. It validates styles and can optimise them; RN uses Flexbox and a subset of CSS-like properties." },
  { cat:"React Native", q:"How does navigation work?", a:"Usually via React Navigation, which provides stack, tab and drawer navigators and a navigation prop to move between screens and pass params." },
  { cat:"React Native", q:"How do you handle touch and gestures?", a:"Use Touchable components or Pressable for taps, and react-native-gesture-handler / Reanimated for complex gestures and smooth animations." },
  { cat:"React Native", q:"How do you call APIs in RN?", a:"With fetch or axios inside useEffect, storing results in state — the same pattern as React, often with a loading indicator." },
  { cat:"React Native", q:"What is AsyncStorage?", a:"An unencrypted, asynchronous key-value store for persisting simple data like tokens or settings on the device." },
  { cat:"React Native", q:"How do you handle device permissions?", a:"Request them at runtime via PermissionsAndroid on Android or libraries like react-native-permissions, and configure Info.plist / AndroidManifest." },
  { cat:"React Native", q:"How do you handle the keyboard?", a:"Wrap inputs in KeyboardAvoidingView, use keyboardShouldPersistTaps on scroll views, and dismiss with Keyboard.dismiss()." },
  { cat:"React Native", q:"What is SafeAreaView?", a:"A component that adds padding to keep content clear of notches, status bars and home indicators on modern devices." },
  { cat:"React Native", q:"What are native modules?", a:"Bridges to platform code (Java/Kotlin, Objective-C/Swift) that expose native functionality to JavaScript when a JS library isn't enough." },
  { cat:"React Native", q:"How do you handle images and assets?", a:"Use the Image component with require() for local assets or a uri for remote ones; manage caching and resizeMode for layout." },
  { cat:"React Native", q:"How does Flexbox work in RN?", a:"RN uses Flexbox for layout by default, with flexDirection defaulting to 'column' (unlike the web's 'row'), plus justifyContent and alignItems." },
  { cat:"React Native", q:"How do you handle screen orientation?", a:"Listen to dimension changes with useWindowDimensions or Dimensions, or lock orientation via config/libraries like react-native-orientation-locker." },
  { cat:"React Native", q:"What is Hermes?", a:"A lightweight JavaScript engine optimised for React Native that improves start-up time, memory use and app size." },
  { cat:"React Native", q:"How do you implement push notifications?", a:"Use Firebase Cloud Messaging (FCM) / APNs via libraries like Notifee or react-native-firebase to receive and display notifications." },
  { cat:"React Native", q:"How do you deploy to the app stores?", a:"Build a signed release (Xcode/Gradle or EAS Build), then submit the .ipa to App Store Connect and the .aab to Google Play Console." },
  { cat:"React Native", q:"What does keyExtractor do in a FlatList?", a:"It gives each list item a unique, stable key so RN can track and recycle rows efficiently." },
  { cat:"React Native", q:"How do you manage environment configs?", a:"Use react-native-config or .env files to keep API URLs and keys per environment, kept out of source control." },
  { cat:"React Native", q:"What state management options exist?", a:"Local state/Context for simple apps; Redux Toolkit, Zustand, MobX or Recoil for larger apps with shared global state." },
  { cat:"React Native", q:"How do you handle offline support?", a:"Detect connectivity with NetInfo, cache data locally, queue actions, and sync when the network returns." },
  { cat:"React Native", q:"How do you test React Native apps?", a:"Unit/component tests with Jest and React Native Testing Library; end-to-end tests with Detox or Maestro." },

  /* ===== Node.js (30) ===== */
  { cat:"Node.js", q:"What is Node.js?", a:"A server-side JavaScript runtime built on V8. It's event-driven and non-blocking, ideal for I/O-heavy, real-time apps and APIs." },
  { cat:"Node.js", q:"Is Node.js single-threaded?", a:"The JS event loop is single-threaded, but Node offloads I/O to libuv's thread pool and the OS, handling many concurrent operations without blocking." },
  { cat:"Node.js", q:"What is middleware in Express?", a:"Functions with access to req, res and next() that run during the request-response cycle for logging, auth, parsing and error handling." },
  { cat:"Node.js", q:"require vs import?", a:"require is CommonJS — synchronous and dynamic. import is ES modules — static, hoisted and tree-shakeable. ESM is the modern standard." },
  { cat:"Node.js", q:"How do you handle async errors?", a:"Use try/catch with async/await, .catch() on promises, error-first callbacks, and centralised Express error middleware; handle unhandledRejection globally." },
  { cat:"Node.js", q:"process.nextTick vs setImmediate?", a:"nextTick callbacks run right after the current operation, before the loop continues. setImmediate runs on the next loop iteration's check phase. nextTick has higher priority." },
  { cat:"Node.js", q:"What is npm and package.json?", a:"npm is Node's package manager. package.json declares dependencies, scripts and metadata; package-lock.json pins exact versions for reproducible installs." },
  { cat:"Node.js", q:"What are streams?", a:"Interfaces that process data in chunks (readable, writable, duplex, transform) instead of loading it all into memory — ideal for large files and piping." },
  { cat:"Node.js", q:"What does event-driven mean in Node?", a:"Node reacts to events via callbacks/emitters rather than waiting. The EventEmitter class lets objects emit and listen for named events." },
  { cat:"Node.js", q:"What is Express?", a:"A minimal, flexible web framework for Node that simplifies routing, middleware, requests and responses for building APIs and web apps." },
  { cat:"Node.js", q:"What are the event loop phases?", a:"timers, pending callbacks, poll, check and close — each handling specific callbacks, with microtasks (promises, nextTick) processed between phases." },
  { cat:"Node.js", q:"What is callback hell and how do you avoid it?", a:"Deeply nested callbacks that are hard to read. Avoid it with named functions, promises, or async/await." },
  { cat:"Node.js", q:"What is libuv?", a:"A C library that gives Node its event loop and asynchronous I/O, including the thread pool for file system and DNS operations." },
  { cat:"Node.js", q:"What are environment variables and dotenv?", a:"Configuration kept outside code (DB URLs, secrets). The dotenv package loads them from a .env file into process.env." },
  { cat:"Node.js", q:"How do you enable CORS in Express?", a:"Use the cors middleware (app.use(cors())) to set Access-Control-Allow-* headers so browsers from other origins can call your API." },
  { cat:"Node.js", q:"How do you implement JWT auth in Node?", a:"Sign a token with jsonwebtoken on login, send it to the client, then verify it in middleware on protected routes." },
  { cat:"Node.js", q:"How do you connect to a database?", a:"Use a driver/ORM — mysql2 or Sequelize for SQL, Mongoose for MongoDB — managing connections via a pool and config from env variables." },
  { cat:"Node.js", q:"What is the cluster module?", a:"It forks multiple worker processes that share a port, letting Node use all CPU cores for better throughput." },
  { cat:"Node.js", q:"What is a Buffer?", a:"A fixed-length container for raw binary data, used when handling streams, files or network packets before converting to strings." },
  { cat:"Node.js", q:"readFile vs createReadStream?", a:"readFile loads the whole file into memory; createReadStream reads it in chunks, which is memory-efficient for large files." },
  { cat:"Node.js", q:"What is an error-first callback?", a:"The Node convention where a callback's first argument is an error (or null), and results follow: callback(err, data)." },
  { cat:"Node.js", q:"What is package-lock.json?", a:"A file that records the exact resolved version of every dependency so installs are identical across machines." },
  { cat:"Node.js", q:"What is the REPL?", a:"Read-Eval-Print-Loop — the interactive Node shell for quickly testing JavaScript expressions." },
  { cat:"Node.js", q:"module.exports vs exports?", a:"module.exports is what a module actually returns. exports is just a reference to it; reassigning exports breaks the link, so export via module.exports." },
  { cat:"Node.js", q:"How do you handle file uploads?", a:"Use the multer middleware to parse multipart/form-data and store files on disk or memory, then access them via req.file/req.files." },
  { cat:"Node.js", q:"What is the global object in Node?", a:"global (like window in browsers) holds globals such as process, console, setTimeout and Buffer available everywhere." },
  { cat:"Node.js", q:"How do you schedule tasks?", a:"Use setTimeout/setInterval for simple timing, or node-cron / a job queue (Bull) for scheduled and background jobs." },
  { cat:"Node.js", q:"dependencies vs devDependencies?", a:"dependencies are needed to run the app in production; devDependencies (test, build, lint tools) are only needed during development." },
  { cat:"Node.js", q:"How do you secure a Node app?", a:"Use HTTPS, helmet for headers, validate input, hash passwords (bcrypt), rate-limit, keep secrets in env, and patch dependencies regularly." },
  { cat:"Node.js", q:"What is the difference between a process and a thread here?", a:"A process has its own memory; Node runs your JS in one process/main thread but uses background threads (libuv pool) and can scale with cluster/worker_threads." },

  /* ===== PHP (30) ===== */
  { cat:"PHP", q:"include vs require?", a:"Both import a file. require throws a fatal error and stops if the file is missing; include only warns and continues. Use require for critical files." },
  { cat:"PHP", q:"== vs === in PHP?", a:"== compares with type juggling; === compares value and type strictly. Prefer === for predictable results." },
  { cat:"PHP", q:"What is PDO?", a:"PHP Data Objects — a consistent, database-agnostic API with prepared statements that prevent SQL injection." },
  { cat:"PHP", q:"How do you prevent SQL injection?", a:"Use prepared statements with bound parameters (PDO/MySQLi) so input is treated as data, never executable SQL; also validate input." },
  { cat:"PHP", q:"What are traits?", a:"A way to reuse methods across classes (horizontal reuse), working around PHP's single inheritance." },
  { cat:"PHP", q:"Sessions vs cookies?", a:"Cookies store data in the browser and are sent each request. Sessions store data on the server, keyed by a session-id cookie — better for sensitive state." },
  { cat:"PHP", q:"Abstract class vs interface?", a:"An abstract class can have implemented and abstract members and is extended (single). An interface only declares method signatures and a class can implement many." },
  { cat:"PHP", q:"What is Composer?", a:"PHP's dependency manager. It reads composer.json, installs packages into vendor/, and provides PSR-4 autoloading." },
  { cat:"PHP", q:"GET vs POST?", a:"GET puts data in the URL, is cacheable and for retrieval. POST sends data in the body, isn't cached, and is for state changes or sensitive data." },
  { cat:"PHP", q:"echo vs print?", a:"Both output text. echo takes multiple arguments and returns nothing; print takes one and returns 1, so it can be used in expressions." },
  { cat:"PHP", q:"What are magic methods?", a:"Special methods prefixed with __ that PHP calls automatically, like __construct, __get, __set, __call and __toString." },
  { cat:"PHP", q:"$_GET vs $_POST vs $_REQUEST?", a:"$_GET reads URL query data, $_POST reads form-body data, and $_REQUEST merges GET, POST and COOKIE (less safe due to ambiguity)." },
  { cat:"PHP", q:"What are namespaces?", a:"They group classes/functions to avoid naming collisions and enable autoloading, e.g. App\\Models\\User." },
  { cat:"PHP", q:"What is PSR-4 autoloading?", a:"A standard mapping namespaces to directory paths so classes load automatically without manual require statements." },
  { cat:"PHP", q:"public, private and protected?", a:"Visibility modifiers: public is accessible anywhere, protected within the class and subclasses, private only within the declaring class." },
  { cat:"PHP", q:"What is type juggling?", a:"PHP automatically converting types in operations/comparisons, e.g. '10' + 5 equals 15. It can cause subtle bugs, hence === is safer." },
  { cat:"PHP", q:"isset() vs empty() vs unset()?", a:"isset checks a variable exists and isn't null; empty checks it's falsy; unset destroys a variable." },
  { cat:"PHP", q:"What does the final keyword do?", a:"final prevents a class from being extended or a method from being overridden." },
  { cat:"PHP", q:"What are anonymous functions / closures?", a:"Functions without a name assigned to variables or passed as callbacks; the use keyword imports outer variables into their scope." },
  { cat:"PHP", q:"What is the spaceship operator?", a:"<=> returns -1, 0 or 1 comparing two values — handy for sorting comparators (usort)." },
  { cat:"PHP", q:"array_merge vs the + operator?", a:"array_merge appends and reindexes numeric keys, with later values overriding string keys. + keeps the left array's keys and ignores duplicates from the right." },
  { cat:"PHP", q:"How does exception handling work?", a:"Wrap risky code in try, catch specific Exception types, optionally finally, and throw your own exceptions to signal errors." },
  { cat:"PHP", q:"Single vs double quotes?", a:"Single-quoted strings are literal. Double-quoted strings parse variables and escape sequences like \\n, so they're slightly slower." },
  { cat:"PHP", q:"What is dependency injection?", a:"Passing a class's dependencies in (via constructor/method) instead of creating them inside, improving testability and decoupling." },
  { cat:"PHP", q:"What is __construct?", a:"The constructor magic method that runs automatically when an object is created, typically to initialise properties." },
  { cat:"PHP", q:"What is late static binding?", a:"Using 'static::' instead of 'self::' so a method resolves to the calling subclass at runtime rather than the class where it was defined." },
  { cat:"PHP", q:"require vs require_once?", a:"require includes a file every time; require_once includes it only if it hasn't been included already, preventing redeclaration errors." },
  { cat:"PHP", q:"What is output buffering?", a:"ob_start() captures output into a buffer instead of sending it immediately, letting you modify or discard it before flushing with ob_get_clean()." },
  { cat:"PHP", q:"Static vs instance methods?", a:"Static methods belong to the class and are called without an object (Class::method()); instance methods need an object and can access $this." },
  { cat:"PHP", q:"What is the difference between an associative and indexed array?", a:"An indexed array uses numeric keys; an associative array uses named string keys. PHP arrays are ordered maps that support both." },

  /* ===== Laravel (30) ===== */
  { cat:"Laravel", q:"What is Eloquent?", a:"Laravel's ORM where each model maps to a table, letting you query and relate data with expressive methods instead of raw SQL." },
  { cat:"Laravel", q:"What is middleware in Laravel?", a:"A filter layer for HTTP requests (auth, CSRF, CORS, logging) that runs before/after controllers and can short-circuit the request." },
  { cat:"Laravel", q:"What is Artisan?", a:"Laravel's CLI for scaffolding code, running migrations, clearing caches, managing queues and custom commands." },
  { cat:"Laravel", q:"What are migrations?", a:"Version control for your database schema, defined in PHP so it can be recreated and shared across environments." },
  { cat:"Laravel", q:"What is the service container?", a:"Laravel's dependency-injection container that automatically resolves and injects class dependencies." },
  { cat:"Laravel", q:"What are facades?", a:"A clean static-like interface (Cache::get()) to services in the container, while remaining testable underneath." },
  { cat:"Laravel", q:"What is the N+1 problem and eager loading?", a:"Running one query per item for a relation. Eager loading with ->with('relation') fetches it all in a couple of queries." },
  { cat:"Laravel", q:"What are queues?", a:"They defer slow tasks (emails, processing) to background workers via drivers like Redis or database, keeping responses fast." },
  { cat:"Laravel", q:"What is CSRF protection?", a:"Laravel adds a token to forms (@csrf) and verifies it, ensuring state-changing requests come from your own app." },
  { cat:"Laravel", q:"What is route model binding?", a:"Laravel auto-injects a model by resolving a route parameter (e.g. /users/{user} loads the User), reducing manual lookups." },
  { cat:"Laravel", q:"What is Blade?", a:"Laravel's templating engine with directives (@if, @foreach), layout inheritance (@extends/@section) and components, compiled to plain PHP." },
  { cat:"Laravel", q:"What are seeders and factories?", a:"Factories define fake model data; seeders insert it into the database for testing and local development." },
  { cat:"Laravel", q:"get() vs first()?", a:"get() returns a collection of all matching rows; first() returns only the first matching model (or null)." },
  { cat:"Laravel", q:"What relationship types does Eloquent support?", a:"hasOne, hasMany, belongsTo, belongsToMany (many-to-many), hasManyThrough and polymorphic relations." },
  { cat:"Laravel", q:"What is a resource controller?", a:"A controller generated with standard CRUD methods (index, create, store, show, edit, update, destroy) wired up by Route::resource()." },
  { cat:"Laravel", q:"How does validation work?", a:"Validate in the controller with $request->validate([...]) or in a dedicated Form Request class; failures auto-redirect with errors." },
  { cat:"Laravel", q:"What are events and listeners?", a:"Events broadcast that something happened; listeners react to them. They decouple side effects (e.g. send email after registration)." },
  { cat:"Laravel", q:"What is the .env file?", a:"Environment-specific configuration (DB, keys, mail) kept out of code and read via config()/env()." },
  { cat:"Laravel", q:"What is a service provider?", a:"The central place to register bindings, events and services into the container during the bootstrap phase." },
  { cat:"Laravel", q:"Describe the request lifecycle.", a:"public/index.php boots the app, the kernel runs middleware, the router dispatches to a controller, a response is built and middleware runs on the way out." },
  { cat:"Laravel", q:"Eloquent vs Query Builder?", a:"Query Builder is a fluent SQL interface returning arrays/stdClass. Eloquent sits on top, returning model objects with relationships and events." },
  { cat:"Laravel", q:"What is soft delete?", a:"Using the SoftDeletes trait marks rows with deleted_at instead of removing them, so they can be restored or queried." },
  { cat:"Laravel", q:"What are accessors and mutators?", a:"Accessors format an attribute when read; mutators transform it before saving — used to keep model data clean." },
  { cat:"Laravel", q:"Session vs cache?", a:"Sessions store per-user data across requests; cache stores shared, temporary data (query results, config) to speed up the app." },
  { cat:"Laravel", q:"What are API resources?", a:"Classes that transform models/collections into a consistent JSON shape, controlling exactly which fields the API returns." },
  { cat:"Laravel", q:"What are middleware groups?", a:"Named bundles of middleware (web, api) applied together to routes, configured in the HTTP kernel." },
  { cat:"Laravel", q:"Sanctum vs Passport?", a:"Sanctum offers lightweight token/SPA auth; Passport is a full OAuth2 server. Use Sanctum unless you need OAuth2." },
  { cat:"Laravel", q:"What is Tinker?", a:"An interactive REPL (php artisan tinker) to run Laravel code, query models and test logic from the command line." },
  { cat:"Laravel", q:"redirect() vs view()?", a:"view() renders and returns a template directly; redirect() sends an HTTP redirect to another URL/route, often after form submissions." },
  { cat:"Laravel", q:"What is dependency injection in Laravel?", a:"Type-hinting dependencies in constructors or methods; the service container resolves and injects them automatically." },

  /* ===== CodeIgniter (30) ===== */
  { cat:"CodeIgniter", q:"What is CodeIgniter?", a:"A lightweight, fast PHP MVC framework with a small footprint and minimal configuration, good for APIs and apps." },
  { cat:"CodeIgniter", q:"Explain the MVC pattern.", a:"Model handles data and business logic, View handles presentation, Controller handles input and coordinates them — separating concerns." },
  { cat:"CodeIgniter", q:"How does routing work in CI4?", a:"Routes in app/Config/Routes.php map HTTP verbs and URL patterns (with placeholders like (:num)) to controller methods." },
  { cat:"CodeIgniter", q:"What is the Query Builder?", a:"A fluent, database-agnostic API for building SQL that automatically escapes values, reducing injection risk." },
  { cat:"CodeIgniter", q:"What are Filters in CI4?", a:"Classes that run before or after controllers (auth, CORS, throttling), registered globally or per-route in Config/Filters.php." },
  { cat:"CodeIgniter", q:"How does CI handle CSRF?", a:"Built-in CSRF protection (configured in Security/Filters) issues a token that must accompany state-changing requests." },
  { cat:"CodeIgniter", q:"CodeIgniter 3 vs 4 — key differences?", a:"CI4 requires PHP 7.4+, uses namespaces and PSR-4 autoloading, has a new routing/filters system, the spark CLI, and improved models/entities." },
  { cat:"CodeIgniter", q:"What are helpers?", a:"Collections of procedural functions for common tasks (form, url, text). You load them and call functions like base_url() or form_open()." },
  { cat:"CodeIgniter", q:"What are libraries?", a:"Class-based components for features like sessions, email, validation and pagination that you instantiate or load as services." },
  { cat:"CodeIgniter", q:"What is the Model in CI4?", a:"A class extending CodeIgniter\\Model that maps to a table and provides CRUD helpers, validation, and query-builder access." },
  { cat:"CodeIgniter", q:"What is a Controller?", a:"A class that handles a request, runs logic/models, and returns a view or response. Methods map to routes." },
  { cat:"CodeIgniter", q:"What is a View?", a:"A PHP template for output, rendered with view('name', $data) and often combined with layouts and view cells." },
  { cat:"CodeIgniter", q:"What are Entities in CI4?", a:"Objects representing a single row with typed properties, casting and business logic, separate from the Model that fetches them." },
  { cat:"CodeIgniter", q:"How do you configure the database?", a:"In app/Config/Database.php or via the .env file (database.default.*), then connect with \\Config\\Database::connect()." },
  { cat:"CodeIgniter", q:"How does validation work?", a:"Define rules via the Validation service or in the model's $validationRules, then call $this->validate() and read getErrors()." },
  { cat:"CodeIgniter", q:"How do sessions work in CI?", a:"The Session service stores per-user data (set/get) and flash data that lasts for the next request only." },
  { cat:"CodeIgniter", q:"What are the request and response objects?", a:"IncomingRequest reads input (getPost, getVar, getJSON); Response builds output, sets headers, status codes and JSON." },
  { cat:"CodeIgniter", q:"How does autoloading work in CI4?", a:"PSR-4 autoloading maps namespaces to folders, configured in app/Config/Autoload.php and composer for third-party packages." },
  { cat:"CodeIgniter", q:"What are events in CI4?", a:"Hooks that let you run code at framework points (pre_system, post_controller) using Events::on() and trigger()." },
  { cat:"CodeIgniter", q:"What is the spark CLI?", a:"CodeIgniter's command-line tool (php spark) for serving the app, running migrations, generating code and custom commands." },
  { cat:"CodeIgniter", q:"How does the .env file work in CI4?", a:"It overrides Config values per environment (database, baseURL, JWT secret) without editing config classes." },
  { cat:"CodeIgniter", q:"base_url() vs site_url()?", a:"base_url() points to the project root (assets), while site_url() builds full app URLs including the index/route path." },
  { cat:"CodeIgniter", q:"getPost() vs getVar()?", a:"getPost() reads only POST data; getVar() reads from GET, POST or cookies (the request input), so getPost is more specific." },
  { cat:"CodeIgniter", q:"How do migrations work in CI4?", a:"Migration classes define up()/down() schema changes; run them with php spark migrate to version-control the database." },
  { cat:"CodeIgniter", q:"What is the BaseController?", a:"A parent controller where you load shared helpers, services and properties so all controllers inherit common setup." },
  { cat:"CodeIgniter", q:"What is method spoofing?", a:"Sending a hidden _method field so HTML forms (which only support GET/POST) can perform PUT/DELETE requests." },
  { cat:"CodeIgniter", q:"getResult() vs getRow()?", a:"getResult() returns all rows (as objects/arrays); getRow() returns a single row. Use the right one to avoid extra work." },
  { cat:"CodeIgniter", q:"How do you enable CORS in CI4?", a:"Set the Access-Control-Allow-* headers in a before-filter or controller, and respond to OPTIONS preflight requests with 204." },
  { cat:"CodeIgniter", q:"How are namespaces structured in CI4?", a:"App code lives under the App namespace (App\\Controllers, App\\Models), mapped via PSR-4, keeping classes organised and autoloadable." },
  { cat:"CodeIgniter", q:"How do you build a REST API in CI4?", a:"Extend ResourceController, set $modelName and $format='json', and implement index/show/create/update/delete with respond() helpers." },

  /* ===== MySQL (30) ===== */
  { cat:"MySQL", q:"SQL vs NoSQL?", a:"SQL is relational with fixed schemas and strong consistency. NoSQL stores flexible documents/key-values and scales horizontally for high-volume, unstructured data." },
  { cat:"MySQL", q:"Primary key vs foreign key?", a:"A primary key uniquely identifies a row and can't be null. A foreign key references another table's primary key, enforcing relationships." },
  { cat:"MySQL", q:"Explain the types of JOINs.", a:"INNER returns matching rows in both tables; LEFT returns all left rows plus matches; RIGHT the reverse; FULL returns all rows with NULLs where unmatched." },
  { cat:"MySQL", q:"WHERE vs HAVING?", a:"WHERE filters rows before grouping; HAVING filters groups after GROUP BY and can use aggregate functions." },
  { cat:"MySQL", q:"What is an index?", a:"A structure that speeds up reads by avoiding full table scans, at the cost of slower writes and extra storage." },
  { cat:"MySQL", q:"What is normalization?", a:"Organising tables (1NF, 2NF, 3NF) to remove redundancy and improve integrity by splitting data into related tables." },
  { cat:"MySQL", q:"DELETE vs TRUNCATE vs DROP?", a:"DELETE removes selected rows (rollback-able). TRUNCATE quickly clears all rows and resets auto-increment. DROP removes the whole table." },
  { cat:"MySQL", q:"What are ACID transactions?", a:"Atomicity, Consistency, Isolation, Durability — guarantees that grouped statements succeed or fail as a unit (BEGIN/COMMIT/ROLLBACK)." },
  { cat:"MySQL", q:"CHAR vs VARCHAR?", a:"CHAR is fixed-length and padded; VARCHAR is variable-length, storing only what's needed plus a length byte — better for variable data." },
  { cat:"MySQL", q:"What is a stored procedure?", a:"A named, precompiled set of SQL statements stored in the database and called by name, useful for reusable logic." },
  { cat:"MySQL", q:"What is a view?", a:"A saved query that acts like a virtual table, simplifying complex joins and restricting which columns users see." },
  { cat:"MySQL", q:"What is a trigger?", a:"A procedure that runs automatically in response to INSERT, UPDATE or DELETE events on a table, used for auditing or enforcing rules." },
  { cat:"MySQL", q:"What are aggregate functions?", a:"Functions that compute over groups: COUNT, SUM, AVG, MIN, MAX — typically used with GROUP BY." },
  { cat:"MySQL", q:"UNION vs UNION ALL?", a:"Both combine result sets with the same columns. UNION removes duplicates (slower); UNION ALL keeps them (faster)." },
  { cat:"MySQL", q:"What is a subquery?", a:"A query nested inside another, used in SELECT, FROM or WHERE to compute a value or set the outer query depends on." },
  { cat:"MySQL", q:"What is AUTO_INCREMENT?", a:"A column attribute that automatically assigns the next sequential integer, typically for primary keys." },
  { cat:"MySQL", q:"What is a composite key?", a:"A primary key made of two or more columns that together uniquely identify a row." },
  { cat:"MySQL", q:"What is a UNIQUE constraint?", a:"It ensures all values in a column (or set) are distinct, allowing one NULL but no duplicates." },
  { cat:"MySQL", q:"What do LIMIT and OFFSET do?", a:"LIMIT restricts the number of rows returned; OFFSET skips a number of rows — together they implement pagination." },
  { cat:"MySQL", q:"COUNT(*) vs COUNT(column)?", a:"COUNT(*) counts all rows; COUNT(column) counts only rows where that column is not NULL." },
  { cat:"MySQL", q:"What is a self join?", a:"A table joined to itself (using aliases) to compare rows within the same table, e.g. employees and their managers." },
  { cat:"MySQL", q:"DISTINCT vs GROUP BY?", a:"DISTINCT removes duplicate rows from output; GROUP BY groups rows so you can apply aggregates per group. They overlap but GROUP BY enables aggregation." },
  { cat:"MySQL", q:"What index types exist?", a:"PRIMARY, UNIQUE, regular (INDEX/KEY), FULLTEXT for text search, and composite indexes spanning multiple columns." },
  { cat:"MySQL", q:"What does EXPLAIN do?", a:"It shows the query execution plan — how MySQL will use indexes, join order and rows scanned — for performance tuning." },
  { cat:"MySQL", q:"BETWEEN vs IN?", a:"BETWEEN matches a continuous range (inclusive); IN matches any value in a specific list." },
  { cat:"MySQL", q:"What is ON DELETE CASCADE?", a:"A foreign-key rule that automatically deletes child rows when the referenced parent row is deleted." },
  { cat:"MySQL", q:"What is denormalization?", a:"Intentionally adding redundancy (duplicating data) to reduce joins and speed up reads, trading storage and write complexity." },
  { cat:"MySQL", q:"DDL vs DML?", a:"DDL defines structure (CREATE, ALTER, DROP); DML manipulates data (SELECT, INSERT, UPDATE, DELETE)." },
  { cat:"MySQL", q:"Clustered vs non-clustered index?", a:"A clustered index (the primary key in InnoDB) determines the physical row order. Non-clustered indexes are separate structures pointing to rows." },
  { cat:"MySQL", q:"WHERE vs ON in a JOIN?", a:"ON defines how tables are joined (the match condition); WHERE filters the combined result afterwards. The distinction matters for outer joins." },

  /* ===== MongoDB (30) ===== */
  { cat:"MongoDB", q:"What is MongoDB?", a:"A document-oriented NoSQL database storing flexible JSON-like BSON documents in collections, with no fixed schema." },
  { cat:"MongoDB", q:"How do Mongo terms map to SQL?", a:"Database to database, collection to table, document to row, field to column — but documents can nest objects and arrays." },
  { cat:"MongoDB", q:"Embedding vs referencing?", a:"Embed related data read together and bounded in size; reference (store an id) for large, shared or independently changing data." },
  { cat:"MongoDB", q:"What is the aggregation pipeline?", a:"A staged framework ($match, $group, $sort, $lookup) to filter, transform and compute results — Mongo's analytics engine." },
  { cat:"MongoDB", q:"What is an index in MongoDB?", a:"A structure that speeds up queries by avoiding full collection scans; supports single, compound, text and geospatial types." },
  { cat:"MongoDB", q:"What is sharding?", a:"Horizontal scaling by distributing a collection across multiple servers using a shard key, for very large datasets." },
  { cat:"MongoDB", q:"What is replication?", a:"A replica set keeps copies across nodes: a primary takes writes, secondaries replicate, giving high availability and failover." },
  { cat:"MongoDB", q:"When choose MongoDB over MySQL?", a:"For unstructured or evolving data, horizontal scale, or documents that map naturally to objects. Choose SQL for strong relations and multi-row transactions." },
  { cat:"MongoDB", q:"What is BSON?", a:"Binary JSON — the efficient binary format MongoDB uses to store documents, supporting extra types like Date, ObjectId and binary data." },
  { cat:"MongoDB", q:"What is _id and ObjectId?", a:"Every document has a unique _id. By default it's an ObjectId — a 12-byte value encoding a timestamp, machine and counter." },
  { cat:"MongoDB", q:"find() vs findOne()?", a:"find() returns a cursor over all matching documents; findOne() returns just the first match (or null)." },
  { cat:"MongoDB", q:"What are the core CRUD methods?", a:"insertOne/insertMany, find/findOne, updateOne/updateMany, and deleteOne/deleteMany." },
  { cat:"MongoDB", q:"What is $lookup?", a:"An aggregation stage that performs a left outer join with another collection, pulling in related documents." },
  { cat:"MongoDB", q:"What is upsert?", a:"An update option that inserts a new document if no match is found, otherwise updates the existing one." },
  { cat:"MongoDB", q:"updateOne vs updateMany?", a:"updateOne modifies the first matching document; updateMany modifies all matches." },
  { cat:"MongoDB", q:"What is projection?", a:"Specifying which fields to include or exclude in query results to reduce payload, e.g. find(query, { name: 1 })." },
  { cat:"MongoDB", q:"$set vs $push?", a:"$set updates or adds a field's value; $push appends a value to an array field." },
  { cat:"MongoDB", q:"What is a capped collection?", a:"A fixed-size collection that overwrites the oldest documents when full, useful for logs and circular buffers." },
  { cat:"MongoDB", q:"What is Mongoose?", a:"An ODM for Node.js that adds schemas, validation, middleware and relationships on top of the MongoDB driver." },
  { cat:"MongoDB", q:"What is schema validation in MongoDB?", a:"Rules (via JSON Schema or Mongoose) that enforce field types and required values even though MongoDB is schema-flexible." },
  { cat:"MongoDB", q:"What is populate in Mongoose?", a:"It replaces referenced ObjectIds with the actual documents from another collection — Mongoose's join-like feature." },
  { cat:"MongoDB", q:"What are write concerns?", a:"Settings that control how many nodes must acknowledge a write before it's considered successful, balancing durability and speed." },
  { cat:"MongoDB", q:"What is read preference?", a:"A setting that decides which replica-set members serve reads (primary, secondary, nearest), trading consistency for load distribution." },
  { cat:"MongoDB", q:"What is a TTL index?", a:"A time-to-live index that automatically deletes documents after a set period — great for sessions and temporary data." },
  { cat:"MongoDB", q:"What does $group do?", a:"An aggregation stage that groups documents by a key and computes accumulators like $sum, $avg or $max per group." },
  { cat:"MongoDB", q:"find() vs aggregate()?", a:"find() does simple filtering/projection; aggregate() runs multi-stage transformations, joins and computations." },
  { cat:"MongoDB", q:"What is GridFS?", a:"A specification for storing and retrieving files larger than the 16MB document limit by splitting them into chunks." },
  { cat:"MongoDB", q:"How does MongoDB handle atomicity?", a:"Single-document operations are atomic; multi-document atomicity requires multi-document transactions (supported in replica sets)." },
  { cat:"MongoDB", q:"deleteOne vs the old remove()?", a:"deleteOne/deleteMany are the current, explicit methods; remove() is deprecated and ambiguous about how many it deletes." },
  { cat:"MongoDB", q:"What are query operators?", a:"Operators like $gt, $lt, $in, $ne, $and, $or used to express conditions in queries beyond simple equality." },

  /* ===== REST & JWT (30) ===== */
  { cat:"REST & JWT", q:"What is a REST API?", a:"An architectural style exposing resources via URLs and manipulating them with stateless HTTP methods; each request is self-contained." },
  { cat:"REST & JWT", q:"What do the main HTTP methods do?", a:"GET reads, POST creates, PUT replaces, PATCH partially updates, DELETE removes. GET/PUT/DELETE are idempotent." },
  { cat:"REST & JWT", q:"What is a JWT?", a:"A signed, self-contained token (header.payload.signature). The server verifies the signature instead of looking up a session, enabling stateless auth." },
  { cat:"REST & JWT", q:"JWT vs session authentication?", a:"Sessions store state server-side with a session-id cookie. JWTs are stateless and carry claims, scaling well but harder to revoke." },
  { cat:"REST & JWT", q:"What is CORS?", a:"A browser security mechanism that blocks cross-origin requests unless the server returns Access-Control-Allow-* headers permitting them." },
  { cat:"REST & JWT", q:"What does idempotent mean?", a:"An operation that gives the same result no matter how many times it's repeated. GET, PUT and DELETE are idempotent; POST usually isn't." },
  { cat:"REST & JWT", q:"What are common status codes?", a:"200 OK, 201 Created, 204 No Content, 400 Bad Request, 401 Unauthorized, 403 Forbidden, 404 Not Found, 422 Validation, 500 Server Error." },
  { cat:"REST & JWT", q:"How do you secure a REST API?", a:"Use HTTPS, token/OAuth auth, input validation, rate limiting, RBAC scoping, and never trust client data; keep secrets out of code." },
  { cat:"REST & JWT", q:"What is statelessness?", a:"The server keeps no client context between requests; each request carries all info needed (e.g. a token), which improves scalability." },
  { cat:"REST & JWT", q:"What are the three parts of a JWT?", a:"Header (algorithm/type), payload (claims like sub and exp), and signature (verifies the token wasn't tampered with), each Base64URL-encoded." },
  { cat:"REST & JWT", q:"What is a refresh token?", a:"A long-lived token used to obtain new short-lived access tokens without re-login, reducing exposure if an access token leaks." },
  { cat:"REST & JWT", q:"What is OAuth?", a:"An authorization framework that lets an app access a user's resources on another service via tokens, without sharing passwords." },
  { cat:"REST & JWT", q:"Authentication vs authorization?", a:"Authentication verifies who you are; authorization decides what you're allowed to do. Auth-n comes first, auth-z second." },
  { cat:"REST & JWT", q:"What is rate limiting?", a:"Restricting how many requests a client can make in a time window to prevent abuse and protect resources (e.g. 100 req/min)." },
  { cat:"REST & JWT", q:"What is API versioning?", a:"Exposing versions (e.g. /api/v1) so you can evolve the API without breaking existing clients." },
  { cat:"REST & JWT", q:"PUT vs PATCH?", a:"PUT replaces the entire resource with the payload; PATCH applies a partial update to specific fields." },
  { cat:"REST & JWT", q:"What is content negotiation?", a:"The client and server agreeing on a response format via headers like Accept (e.g. application/json vs application/xml)." },
  { cat:"REST & JWT", q:"REST vs SOAP?", a:"REST is lightweight, uses JSON over HTTP and is flexible. SOAP is a strict XML-based protocol with built-in standards, heavier but more rigid." },
  { cat:"REST & JWT", q:"REST vs GraphQL?", a:"REST exposes fixed endpoints; GraphQL exposes one endpoint where clients request exactly the fields they need, avoiding over/under-fetching." },
  { cat:"REST & JWT", q:"How do you implement pagination?", a:"Offset/limit (page-based) or cursor-based pagination, returning metadata like total, page and next cursor so clients can page through data." },
  { cat:"REST & JWT", q:"What is a bearer token?", a:"A token sent in the Authorization header as 'Bearer <token>'; possessing it grants access, so it must be sent over HTTPS." },
  { cat:"REST & JWT", q:"What is an API gateway?", a:"A single entry point in front of services that handles routing, auth, rate limiting, caching and aggregation." },
  { cat:"REST & JWT", q:"401 vs 403?", a:"401 Unauthorized means you're not authenticated (no/invalid credentials). 403 Forbidden means you're authenticated but lack permission." },
  { cat:"REST & JWT", q:"How does CRUD map to HTTP?", a:"Create to POST, Read to GET, Update to PUT/PATCH, Delete to DELETE." },
  { cat:"REST & JWT", q:"What is the role of HTTP headers?", a:"They carry metadata: Content-Type, Authorization, Accept, caching directives and CORS info that shape how requests/responses are handled." },
  { cat:"REST & JWT", q:"What is a webhook?", a:"A server-to-server callback: instead of polling, one system sends an HTTP request to your URL when an event occurs (e.g. payment success)." },
  { cat:"REST & JWT", q:"How should you handle errors in REST?", a:"Return the right status code plus a consistent JSON error body (code, message, details) so clients can react programmatically." },
  { cat:"REST & JWT", q:"What is HATEOAS?", a:"Hypermedia As The Engine Of Application State — responses include links to related actions, so clients navigate the API dynamically." },
  { cat:"REST & JWT", q:"Where should you store a JWT on the client?", a:"In an httpOnly cookie (safer against XSS) or memory. Storing in localStorage is convenient but exposed to XSS attacks." },
  { cat:"REST & JWT", q:"Why do JWTs expire?", a:"Short expiry (exp claim) limits the damage if a token is stolen, since stateless tokens can't be easily revoked server-side." },

  /* ===== HTML & CSS (30) ===== */
  { cat:"HTML & CSS", q:"What is semantic HTML?", a:"Using meaningful tags (header, nav, main, article, footer) instead of generic divs, improving accessibility, SEO and readability." },
  { cat:"HTML & CSS", q:"Block vs inline elements?", a:"Block elements start on a new line and take full width (div, p). Inline elements flow within a line and take only needed space (span, a)." },
  { cat:"HTML & CSS", q:"Explain the CSS box model.", a:"Each element is content + padding + border + margin. box-sizing: border-box makes width include padding and border." },
  { cat:"HTML & CSS", q:"Flexbox vs Grid?", a:"Flexbox is one-dimensional (row or column), great for components. Grid is two-dimensional (rows and columns), great for page layouts." },
  { cat:"HTML & CSS", q:"What do the position values do?", a:"static (default), relative (offset from itself), absolute (to nearest positioned ancestor), fixed (to viewport), sticky (relative until a scroll threshold)." },
  { cat:"HTML & CSS", q:"How does specificity work?", a:"Inline > IDs > classes/attributes/pseudo-classes > elements; !important overrides all. Ties go to the later rule." },
  { cat:"HTML & CSS", q:"px vs em vs rem?", a:"px is fixed, em is relative to the parent font size, rem is relative to the root font size. rem is preferred for scalable, accessible sizing." },
  { cat:"HTML & CSS", q:"How do you make a site responsive?", a:"Fluid layouts (%, flex, grid), relative units, flexible images and media queries; design mobile-first and test across sizes." },
  { cat:"HTML & CSS", q:"Pseudo-class vs pseudo-element?", a:"A pseudo-class targets a state (:hover, :focus). A pseudo-element styles a part of an element (::before, ::after, ::first-line)." },
  { cat:"HTML & CSS", q:"id vs class?", a:"An id is unique per page with higher specificity; a class is reusable. Prefer classes for styling, ids for unique hooks/anchors." },
  { cat:"HTML & CSS", q:"div vs span?", a:"div is a block-level generic container; span is an inline generic container. Use them when no semantic tag fits." },
  { cat:"HTML & CSS", q:"What does the viewport meta tag do?", a:"<meta name='viewport' content='width=device-width, initial-scale=1'> makes the page scale to the device width for proper mobile rendering." },
  { cat:"HTML & CSS", q:"visibility: hidden vs display: none?", a:"visibility: hidden hides the element but keeps its space. display: none removes it from layout entirely." },
  { cat:"HTML & CSS", q:"What is z-index?", a:"It controls the stacking order of positioned elements; higher values appear in front. It only works on positioned elements." },
  { cat:"HTML & CSS", q:"What are media queries?", a:"CSS rules that apply styles based on conditions like screen width, enabling responsive breakpoints (@media (max-width: 768px))." },
  { cat:"HTML & CSS", q:"Inline vs internal vs external CSS?", a:"Inline is on the element (style=''), internal is in a <style> tag, external is a linked .css file. External is best for reuse and caching." },
  { cat:"HTML & CSS", q:"Why is the alt attribute important?", a:"It describes an image for screen readers and shows if the image fails to load, aiding accessibility and SEO." },
  { cat:"HTML & CSS", q:"padding vs margin?", a:"Padding is space inside the border (between content and edge); margin is space outside the border (between elements)." },
  { cat:"HTML & CSS", q:"What is the CSS cascade?", a:"The algorithm that resolves conflicting rules using importance, specificity and source order to decide which style wins." },
  { cat:"HTML & CSS", q:"What are CSS variables?", a:"Custom properties (--color: #333) defined once and reused with var(--color), enabling theming and easier maintenance." },
  { cat:"HTML & CSS", q:"Transition vs animation?", a:"Transitions animate between two states on a trigger (hover). Animations use @keyframes for multi-step, looping or autonomous motion." },
  { cat:"HTML & CSS", q:"width: auto vs width: 100%?", a:"auto sizes to content/available space respecting margins; 100% forces full parent width and can overflow if padding/border are added (without border-box)." },
  { cat:"HTML & CSS", q:"What is box-sizing?", a:"It defines whether width/height include padding and border. border-box includes them, making sizing predictable." },
  { cat:"HTML & CSS", q:"What do float and clear do?", a:"float pushes an element left/right and lets content wrap around it; clear prevents elements from wrapping beside floats. Largely replaced by flex/grid." },
  { cat:"HTML & CSS", q:"nth-child vs nth-of-type?", a:"nth-child matches by position among all siblings; nth-of-type matches by position among siblings of the same tag." },
  { cat:"HTML & CSS", q:"absolute vs fixed positioning?", a:"absolute positions relative to the nearest positioned ancestor and scrolls with the page; fixed positions relative to the viewport and stays put." },
  { cat:"HTML & CSS", q:"What is a CSS reset / normalize?", a:"A stylesheet that removes or standardises default browser styles so your design looks consistent across browsers." },
  { cat:"HTML & CSS", q:"What is web accessibility (a11y)?", a:"Building sites usable by everyone, including assistive tech — via semantic HTML, alt text, ARIA, keyboard navigation and sufficient contrast." },
  { cat:"HTML & CSS", q:"What is the difference between rem-based and px-based layouts?", a:"rem layouts scale with the user's root font-size preference (more accessible); px layouts stay fixed regardless of user settings." },
  { cat:"HTML & CSS", q:"How do you center a div?", a:"With Flexbox: display:flex; justify-content:center; align-items:center on the parent. Or margin:auto with a set width for horizontal centering." },

  /* ===== Git (30) ===== */
  { cat:"Git", q:"git merge vs rebase?", a:"merge combines branches with a merge commit, preserving history. rebase replays commits onto another branch for a linear history. Don't rebase shared branches." },
  { cat:"Git", q:"git fetch vs git pull?", a:"fetch downloads remote changes without touching your branch. pull is fetch + merge (or rebase), integrating them in one step." },
  { cat:"Git", q:"git reset vs git revert?", a:"reset moves the branch pointer and can rewrite history (local use). revert creates a new commit that undoes a previous one (safe for shared branches)." },
  { cat:"Git", q:"What is a merge conflict and how do you resolve it?", a:"It happens when two branches change the same lines. Git marks the conflict; you edit to keep the right version, remove markers, then add and commit/continue." },
  { cat:"Git", q:"What is the staging area?", a:"An intermediate area where you assemble exactly what goes into the next commit. git add stages; git commit records what's staged." },
  { cat:"Git", q:"What is HEAD?", a:"A pointer to the current commit/branch you have checked out, determining what your working directory reflects." },
  { cat:"Git", q:"What does git stash do?", a:"Shelves uncommitted changes to give you a clean working directory; git stash pop reapplies them later." },
  { cat:"Git", q:"Fork vs clone?", a:"A clone is a local copy you can push to (with access). A fork is your own server-side copy of someone's repo, used to contribute via pull requests." },
  { cat:"Git", q:"What is Git?", a:"A distributed version-control system that tracks code changes over time, enabling branching, collaboration and full history on every clone." },
  { cat:"Git", q:"What is a commit?", a:"A snapshot of your staged changes with a message, author and unique hash, forming a node in the project history." },
  { cat:"Git", q:"What is a branch?", a:"A lightweight movable pointer to a commit, letting you develop features in isolation from the main line." },
  { cat:"Git", q:"What is 'origin'?", a:"The default name Git gives to the remote repository you cloned from or added; you push/pull against it." },
  { cat:"Git", q:"What does git cherry-pick do?", a:"It applies a single commit from another branch onto your current branch by its hash." },
  { cat:"Git", q:"What is .gitignore?", a:"A file listing patterns Git should ignore (node_modules, .env, build output) so they're not tracked or committed." },
  { cat:"Git", q:"What does git log show?", a:"The commit history — hashes, authors, dates and messages. Flags like --oneline and --graph make it compact and visual." },
  { cat:"Git", q:"soft vs mixed vs hard reset?", a:"--soft keeps changes staged, --mixed (default) keeps them unstaged, --hard discards them entirely. Use --hard with caution." },
  { cat:"Git", q:"What is interactive rebase?", a:"git rebase -i lets you squash, reorder, edit or drop recent commits to clean up history before sharing." },
  { cat:"Git", q:"What is a detached HEAD?", a:"When HEAD points directly to a commit rather than a branch. New commits there can be lost unless you create a branch." },
  { cat:"Git", q:"What is a git tag?", a:"A named marker for a specific commit, usually a release version (v1.0.0). Annotated tags also store a message and author." },
  { cat:"Git", q:"Local vs remote repository?", a:"The local repo is on your machine (full history, fast operations); the remote (e.g. GitHub) is the shared copy you push to and pull from." },
  { cat:"Git", q:"What does git diff show?", a:"The line-by-line changes — unstaged by default, --staged for staged changes, or between commits/branches." },
  { cat:"Git", q:"What does git blame do?", a:"It annotates each line of a file with the commit and author that last changed it, useful for tracing history." },
  { cat:"Git", q:"What is a pull request?", a:"A request to merge your branch into another, enabling code review, discussion and CI checks before integration (a platform feature, not core git)." },
  { cat:"Git", q:"What is git reflog?", a:"A log of where HEAD has pointed recently — your safety net to recover commits 'lost' after a reset or rebase." },
  { cat:"Git", q:"What does merge --squash do?", a:"It combines all of a branch's changes into a single staged change set, so you record one tidy commit instead of many." },
  { cat:"Git", q:"What is git bisect?", a:"A binary search through history that helps pinpoint the exact commit that introduced a bug." },
  { cat:"Git", q:"What is upstream?", a:"The remote branch your local branch tracks; set with -u so plain git push/pull know where to go." },
  { cat:"Git", q:"Working directory vs staging vs repository?", a:"Working directory holds your edits, the staging area holds what's queued for commit, and the repository stores committed history." },
  { cat:"Git", q:"What does git commit --amend do?", a:"It replaces the last commit to fix its message or include forgotten changes. Avoid amending commits you've already pushed." },
  { cat:"Git", q:"What is a git submodule?", a:"A repository embedded inside another at a fixed commit, used to include external projects while keeping their history separate." },

  /* ===== HR / Behavioural (30) ===== */
  { cat:"HR / Behavioural", q:"Tell me about yourself.", a:"Give a tight summary: your role and experience, two or three relevant highlights, and why this position excites you. Keep it under ~90 seconds and tailored." },
  { cat:"HR / Behavioural", q:"Why should we hire you?", a:"Map your strengths to their needs: name specific skills and a concrete result you've delivered, then show enthusiasm for their product and team." },
  { cat:"HR / Behavioural", q:"What is your greatest strength?", a:"Pick one relevant to the role and back it with a real example and outcome, rather than a generic adjective." },
  { cat:"HR / Behavioural", q:"What is your greatest weakness?", a:"Name a genuine but non-critical weakness and, importantly, the concrete steps you're taking to improve it." },
  { cat:"HR / Behavioural", q:"Why do you want to work here?", a:"Show research: reference their product, stack, mission or culture, and connect it to your own goals and what you can contribute." },
  { cat:"HR / Behavioural", q:"Where do you see yourself in 5 years?", a:"Show ambition and commitment: growing technical depth, taking on more ownership, and adding value — framed as growing with the company." },
  { cat:"HR / Behavioural", q:"Describe a challenging project.", a:"Use STAR: the Situation and Task, the Actions you took and decisions you made, and the measurable Result." },
  { cat:"HR / Behavioural", q:"How do you handle tight deadlines and pressure?", a:"Prioritise ruthlessly, break work into milestones, communicate risks early and stay calm. Back it with a short example." },
  { cat:"HR / Behavioural", q:"Do you have any questions for us?", a:"Always yes. Ask about team structure, the stack and challenges, what success looks like, and growth opportunities." },
  { cat:"HR / Behavioural", q:"Why are you leaving your current job?", a:"Stay positive — focus on seeking growth, new challenges or better alignment, never badmouthing your employer." },
  { cat:"HR / Behavioural", q:"How do you handle conflict with a teammate?", a:"Listen to understand, focus on the problem not the person, find common ground, and escalate only if needed. Give a brief example." },
  { cat:"HR / Behavioural", q:"Tell me about a time you failed.", a:"Pick a real failure, own it honestly, and emphasise what you learned and changed afterwards. Growth matters more than the mistake." },
  { cat:"HR / Behavioural", q:"How do you handle feedback and criticism?", a:"Welcome it as a way to improve, ask clarifying questions, act on it, and follow up. Show you're not defensive." },
  { cat:"HR / Behavioural", q:"What motivates you?", a:"Be authentic — solving hard problems, shipping things users love, learning, or seeing impact. Tie it to the role." },
  { cat:"HR / Behavioural", q:"How do you prioritise tasks?", a:"Assess impact and urgency, align with team goals, break work down, and communicate trade-offs. Mention a method you use (e.g. impact/effort)." },
  { cat:"HR / Behavioural", q:"Describe your ideal work environment.", a:"Describe something honest yet adaptable: collaborative, clear goals, learning culture, and autonomy — ideally matching their setup." },
  { cat:"HR / Behavioural", q:"Are you a team player or an individual contributor?", a:"Show you can do both: you deliver independently but collaborate, share knowledge and help the team succeed." },
  { cat:"HR / Behavioural", q:"How do you keep your skills updated?", a:"Mention concrete habits: building side projects, reading docs/blogs, courses, following the community, and learning on the job." },
  { cat:"HR / Behavioural", q:"What is your biggest achievement?", a:"Choose a relevant accomplishment, quantify the impact, and explain your specific contribution using STAR." },
  { cat:"HR / Behavioural", q:"How do you handle disagreement with your manager?", a:"Share your view respectfully with data, listen to theirs, and commit to the decision once made. Disagree and commit." },
  { cat:"HR / Behavioural", q:"Tell me about a time you went above and beyond.", a:"Describe a situation where you took extra initiative, the action you took, and the positive result for users or the team." },
  { cat:"HR / Behavioural", q:"How do you manage multiple projects at once?", a:"Prioritise by impact, time-box and track work, communicate status, and set realistic expectations to avoid overcommitting." },
  { cat:"HR / Behavioural", q:"What are your salary expectations?", a:"Give a researched range based on the role, market and your experience, and show flexibility. Deflect politely early in the process if needed." },
  { cat:"HR / Behavioural", q:"Why should we choose you over other candidates?", a:"Highlight your unique mix of skills, relevant results and culture fit, focusing on the value you'll add rather than criticising others." },
  { cat:"HR / Behavioural", q:"How do you handle a missed deadline?", a:"Communicate early, explain the cause honestly, propose a recovery plan, and reflect on how to prevent it next time." },
  { cat:"HR / Behavioural", q:"Describe a time you led a team or initiative.", a:"Use STAR: the goal, how you organised people and work, how you handled obstacles, and the outcome — even informal leadership counts." },
  { cat:"HR / Behavioural", q:"How do you deal with ambiguity?", a:"Clarify what you can, make reasonable assumptions, start small, and iterate while keeping stakeholders informed." },
  { cat:"HR / Behavioural", q:"What do you do if you disagree with a requirement?", a:"Ask why it exists, share your concerns with data and alternatives, and align on the goal — then support the final decision." },
  { cat:"HR / Behavioural", q:"How do you onboard to a new codebase?", a:"Read the docs and run the app, explore the architecture, trace key flows, ask focused questions, and start with small tasks." },
  { cat:"HR / Behavioural", q:"Do you prefer frontend or backend, and why?", a:"Be honest but show range: state your preference and strength while demonstrating you're comfortable across the stack and adaptable to needs." },
];
